# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: 'Deploy_Prod'
   
  pool:
      Default
  jobs:
  - deployment: 'Deploy_Prod'
    displayName: 'Deploy_Prod'
    environment: PROD 
  - job: 'Build_Artifact' 

    steps:
    - script: |
        cd $(System.DefaultWorkingDirectory)
        dir

    - script: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel pytest
        python -m pip install -r $(System.DefaultWorkingDirectory)\requirements.txt
      displayName: "Install dependencies"
      
    - script: |
        python -m pytest tests
      displayName: "Run Unit Tests"

    - script: |
        python setup.py bdist_wheel
      displayName: "Make wheel"
    
    - publish: $(System.DefaultWorkingDirectory)/dist
      artifact: PANDASETL_PACKAGE
    - publish: $(System.DefaultWorkingDirectory)/notebooks
      artifact: PANDASETL_NOTEBOOKS
  - job: 'Deploy_Artifact'
    #steps:  
